### PR TITLE
Authenticating with case insensitive email address

### PR DESCRIPTION
**Pull request by kencung**

### CODE REVIEW

**Comment by kencung** [comment]
@don-github Please review

**Comment by kencung** [comment]
thanks Don

**Comment by don-github** [comment]
Thank you, Ken.  I was wondering if it's possible to introduce an external flag/property to their existing application.yml so that we can turn on/off this case-insensitive check.  Was just thinking of having your enhancement without breaking their original implementation.   Thought?  Thanks.

**Comment by kencung** [comment]
@don-github good idea, Don.  I'll give it a try

**Comment by kencung** [comment]
@don-github Please take a look when you have a chance. Thanks

**Comment by don-github** [comment]
+1 Approve Looks great.  Thanks, Ken.

**Pull request merged**
